SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS AddressEntity CASCADE;
DROP TABLE IF EXISTS AddressEntity_CustomerEntity CASCADE;
DROP TABLE IF EXISTS BrandEntity CASCADE;
DROP TABLE IF EXISTS CategoryEntity CASCADE;
DROP TABLE IF EXISTS ColorEntity CASCADE;
DROP TABLE IF EXISTS CouponEntity CASCADE;
DROP TABLE IF EXISTS CreditCardEntity CASCADE;
DROP TABLE IF EXISTS CustomerEntity CASCADE;
DROP TABLE IF EXISTS CustomerEntity_AddressEntity CASCADE;
DROP TABLE IF EXISTS ModelEntity CASCADE;
DROP TABLE IF EXISTS OrderEntity CASCADE;
DROP TABLE IF EXISTS OrderItemEntity CASCADE;
DROP TABLE IF EXISTS ProductEntity CASCADE;
DROP TABLE IF EXISTS ProductEntity_PromotionEntity CASCADE;
DROP TABLE IF EXISTS ProductEntity_TagEntity CASCADE;
DROP TABLE IF EXISTS PromotionEntity CASCADE;
DROP TABLE IF EXISTS PromotionEntity_ProductEntity CASCADE;
DROP TABLE IF EXISTS ReviewEntity CASCADE;
DROP TABLE IF EXISTS SaleEntity CASCADE;
DROP TABLE IF EXISTS SizeEntity CASCADE;
DROP TABLE IF EXISTS SpecificationEntity CASCADE;
DROP TABLE IF EXISTS StaffEntity CASCADE;
DROP TABLE IF EXISTS TagEntity CASCADE;
DROP TABLE IF EXISTS TagEntity_ProductEntity CASCADE;

DROP TABLE IF EXISTS Sequence CASCADE;

SET FOREIGN_KEY_CHECKS = 1;